"""Bangla and Banglish query expansion helpers."""

import re


BANGLA_DIGITS = str.maketrans({
    "০": "0",
    "১": "1",
    "২": "2",
    "৩": "3",
    "৪": "4",
    "৫": "5",
    "৬": "6",
    "৭": "7",
    "৮": "8",
    "৯": "9",
})


PHRASE_TRANSLATIONS = [
    ("assalamu alaikum", "salam hi greeting"),
    ("salam", "salam hi greeting"),
    ("সালাম", "salam hi greeting"),
    ("আসসালামু আলাইকুম", "salam hi greeting"),
    ("হ্যালো", "hello hi greeting"),
    ("হাই", "hi greeting"),
    ("apni ke", "who are you identity"),
    ("tumi ke", "who are you identity"),
    ("apnar nam ki", "what is your name identity"),
    ("আপনি কে", "who are you identity"),
    ("তুমি কে", "who are you identity"),
    ("আপনার নাম কি", "what is your name identity"),
    ("schedule of charges", "schedule of charges"),
    ("schedule charge", "schedule of charges"),
    ("charges schedule", "schedule of charges"),
    ("শিডিউল অফ চার্জেস", "schedule of charges"),
    ("শিডিউল অফ চার্জ", "schedule of charges"),
    ("চার্জ তালিকা", "schedule of charges"),
    ("চার্জের তালিকা", "schedule of charges"),
    ("ফি তালিকা", "schedule of charges fee charge"),
    ("account khulte chai", "open account account opening"),
    ("account khulbo", "open account account opening"),
    ("account khulte", "open account account opening"),
    ("hisab khulte chai", "open account account opening"),
    ("hishab khulte chai", "open account account opening"),
    ("হিসাব খুলতে চাই", "open account account opening"),
    ("একাউন্ট খুলতে চাই", "open account account opening"),
    ("অ্যাকাউন্ট খুলতে চাই", "open account account opening"),
    ("সেভিংস একাউন্ট", "savings account"),
    ("সঞ্চয়ী হিসাব", "savings account"),
    ("সঞ্চয়ী হিসাবের ফি", "savings account maintenance fee charge"),
    ("সঞ্চয়ী হিসাবের ফি", "savings account maintenance fee charge"),
    ("সেভিংস একাউন্টের ফি", "savings account maintenance fee charge"),
    ("savings account fee", "savings account maintenance fee charge"),
    ("saving account fee", "savings account maintenance fee charge"),
    ("চলতি হিসাব", "current account"),
    ("current account", "current account"),
    ("fixed deposit", "fixed deposit fd fdr term deposit"),
    ("মেয়াদী আমানত", "fixed deposit fd fdr term deposit"),
    ("মেয়াদী আমানত", "fixed deposit fd fdr term deposit"),
    ("ডিপিএস", "dps recurring deposit"),
    ("dps", "dps recurring deposit"),
    ("deposit rate", "deposit interest rate"),
    ("ডিপোজিট রেট", "deposit interest rate"),
    ("আমানতের মুনাফা", "deposit interest rate"),
    ("loan rate", "lending interest rate loan rate"),
    ("lending rate", "lending interest rate loan rate"),
    ("লোন রেট", "lending interest rate loan rate"),
    ("ঋণের সুদ", "lending interest rate loan rate"),
    ("home loan", "home loan mortgage housing"),
    ("হোম লোন", "home loan mortgage housing"),
    ("বাড়ি ঋণ", "home loan mortgage housing"),
    ("personal loan", "personal loan"),
    ("পার্সোনাল লোন", "personal loan"),
    ("auto loan", "auto loan car loan vehicle loan"),
    ("car loan", "auto loan car loan vehicle loan"),
    ("গাড়ির লোন", "auto loan car loan vehicle loan"),
    ("education loan", "education loan edu loan student loan"),
    ("student loan", "education loan edu loan student loan"),
    ("credit card", "credit card"),
    ("ক্রেডিট কার্ড", "credit card"),
    ("debit card", "debit card"),
    ("ডেবিট কার্ড", "debit card"),
    ("prepaid card", "prepaid card"),
    ("প্রিপেইড কার্ড", "prepaid card"),
    ("card support", "card support card information"),
    ("কার্ড সাপোর্ট", "card support card information"),
    ("card hariye geche", "lost card card lost urgent card issue"),
    ("card harai geche", "lost card card lost urgent card issue"),
    ("কার্ড হারিয়ে গেছে", "lost card card lost urgent card issue"),
    ("কার্ড হারিয়ে গেছে", "lost card card lost urgent card issue"),
    ("card block", "block card urgent card issue"),
    ("কার্ড ব্লক", "block card urgent card issue"),
    ("cash withdrawal", "cash withdrawal atm"),
    ("ক্যাশ উইথড্রয়াল", "cash withdrawal atm"),
    ("ক্যাশ উত্তোলন", "cash withdrawal atm"),
    ("pin replacement", "pin replacement"),
    ("pin change", "pin change"),
    ("পিন পরিবর্তন", "pin change replacement"),
    ("cheque book", "cheque book"),
    ("check book", "cheque book"),
    ("চেক বই", "cheque book"),
    ("supplementary card", "supplementary card"),
    ("সাপ্লিমেন্টারি কার্ড", "supplementary card"),
    ("processing fee", "processing fee charge"),
    ("প্রসেসিং ফি", "processing fee charge"),
    ("replacement fee", "replacement fee charge"),
    ("রিপ্লেসমেন্ট ফি", "replacement fee charge"),
    ("annual fee", "annual fee yearly charge"),
    ("বার্ষিক ফি", "annual fee yearly charge"),
    ("maintenance fee", "maintenance fee charge"),
    ("মেইনটেন্যান্স ফি", "maintenance fee charge"),
    ("account closing", "account closing charge"),
    ("closing charge", "closing charge fee"),
    ("হিসাব বন্ধ", "account closing charge"),
    ("branch kothay", "branch location branch locator"),
    ("branch koi", "branch location branch locator"),
    ("শাখা কোথায়", "branch location branch locator"),
    ("ব্রাঞ্চ কোথায়", "branch location branch locator"),
    ("contact number", "contact phone number hotline"),
    ("phone number", "contact phone number hotline"),
    ("যোগাযোগ নম্বর", "contact phone number hotline"),
    ("হটলাইন নম্বর", "hotline contact phone number"),
    ("online apply", "online apply application link"),
    ("apply online", "online apply application link"),
    ("অনলাইন আবেদন", "online apply application link"),
    ("complaint status", "complaint status track complaint"),
    ("অভিযোগের স্ট্যাটাস", "complaint status track complaint"),
    ("transaction failed", "failed transaction complaint"),
    ("লেনদেন ব্যর্থ", "failed transaction complaint"),
    ("taka kete niyeche", "money deducted transaction complaint"),
    ("taka kete geche", "money deducted transaction complaint"),
    ("টাকা কেটে নিয়েছে", "money deducted transaction complaint"),
    ("টাকা কেটে গেছে", "money deducted transaction complaint"),
    ("refund paini", "refund not received complaint"),
    ("রিফান্ড পাইনি", "refund not received complaint"),
    ("amar first text", "my first text memory question"),
    ("age ki jiggesh", "previous question memory question"),
    ("আগে কি জিজ্ঞেস", "previous question memory question"),
]


WORD_TRANSLATIONS = {
    "ami": "i",
    "amar": "my",
    "amr": "my",
    "er": "of",
    "jonno": "for",
    "jonne": "for",
    "ki": "what",
    "ke": "who",
    "apni": "you",
    "apnar": "your",
    "tumi": "you",
    "tomar": "your",
    "salam": "salam hi greeting",
    "assalamu": "salam hi greeting",
    "alaikum": "salam hi greeting",
    "hello": "hello hi greeting",
    "hi": "hi greeting",
    "jante": "know",
    "janate": "know",
    "chai": "want",
    "chay": "want",
    "dorkar": "need required",
    "lage": "need required",
    "lagbe": "need required",
    "koto": "how much",
    "koto?": "how much",
    "koto taka": "how much amount",
    "koto tk": "how much amount",
    "koto charge": "how much charge",
    "fee": "fee charge",
    "fees": "fee charge",
    "charge": "charge fee",
    "charges": "charge fee",
    "khoroch": "cost charge fee",
    "khroch": "cost charge fee",
    "mashul": "fee charge",
    "vat": "vat",
    "hisab": "account",
    "hishab": "account",
    "account": "account",
    "ekti": "one",
    "khulbo": "open account",
    "khulte": "open account",
    "khola": "open account",
    "open": "open",
    "bondho": "closing close",
    "close": "closing close",
    "closing": "closing close",
    "saving": "saving savings",
    "savings": "saving savings",
    "sonchoy": "saving savings",
    "shonchoy": "saving savings",
    "current": "current",
    "cholti": "current",
    "deposit": "deposit",
    "amanot": "deposit",
    "amanat": "deposit",
    "fd": "fd fixed deposit",
    "fdr": "fd fdr fixed deposit",
    "fixed": "fixed deposit",
    "dps": "dps recurring deposit",
    "rate": "rate interest",
    "rates": "rate interest",
    "sud": "interest",
    "shud": "interest",
    "interest": "interest rate",
    "munafa": "profit interest rate",
    "profit": "profit interest rate",
    "har": "rate",
    "loan": "loan",
    "loans": "loan",
    "lon": "loan",
    "rin": "loan",
    "home": "home",
    "bari": "home house",
    "gari": "car vehicle auto",
    "car": "car vehicle auto",
    "auto": "auto car vehicle",
    "personal": "personal",
    "education": "education student edu",
    "student": "student education",
    "card": "card",
    "cards": "card",
    "credit": "credit",
    "debit": "debit",
    "prepaid": "prepaid",
    "visa": "visa",
    "mastercard": "mastercard",
    "diners": "diners",
    "pin": "pin",
    "cheque": "cheque check",
    "check": "cheque check",
    "boi": "book",
    "book": "book",
    "atm": "atm",
    "cash": "cash",
    "withdraw": "withdrawal",
    "withdrawal": "withdrawal",
    "replacement": "replacement",
    "replace": "replacement",
    "change": "change replacement",
    "supplementary": "supplementary",
    "primary": "primary",
    "annual": "annual yearly",
    "yearly": "annual yearly",
    "bochor": "year",
    "bochore": "yearly annual",
    "monthly": "monthly",
    "mashik": "monthly",
    "maintenance": "maintenance",
    "processing": "processing",
    "renewal": "renewal",
    "issue": "issue issuance",
    "issuance": "issuance issue",
    "limit": "limit",
    "increase": "increase",
    "branch": "branch",
    "brance": "branch",
    "shakha": "branch",
    "kothay": "where location",
    "koi": "where location",
    "address": "address location",
    "location": "location",
    "contact": "contact",
    "phone": "phone number",
    "number": "number",
    "namber": "number",
    "hotline": "hotline",
    "email": "email",
    "mail": "email",
    "support": "support",
    "complaint": "complaint",
    "complain": "complaint",
    "ovijog": "complaint",
    "obhijog": "complaint",
    "problem": "problem issue",
    "somossa": "problem issue",
    "shomossha": "problem issue",
    "issue": "issue problem",
    "transaction": "transaction",
    "len-den": "transaction",
    "failed": "failed",
    "fail": "failed",
    "deduct": "deducted",
    "deducted": "deducted",
    "kata": "deducted",
    "kete": "deducted",
    "refund": "refund",
    "paini": "not received missing",
    "hariye": "lost",
    "harai": "lost",
    "lost": "lost",
    "stolen": "stolen",
    "churi": "stolen",
    "block": "block",
    "blocked": "blocked",
    "unauthorized": "unauthorized fraud",
    "fraud": "fraud",
    "login": "login",
    "password": "password",
    "pass": "password",
    "otp": "otp",
    "cvv": "cvv",
    "nid": "nid",
    "passport": "passport",
    "nominee": "nominee",
    "kyc": "kyc",
    "documents": "documents required",
    "document": "documents required",
    "kagoj": "documents required",
    "papers": "documents required",
    "retail": "retail",
    "sme": "sme",
    "corporate": "corporate",
    "corp": "corporate corp",
    "islamic": "islamic",
    "shariah": "shariah islamic",
    "army": "army",
    "senabahini": "army",
    "sena": "army",
    "airforce": "air force",
    "bimanbahini": "air force",
    "biman": "air force",
    "navy": "navy",
    "noubahini": "navy",
    "nou": "navy",
    "apply": "apply application",
    "abedon": "apply application",
    "online": "online",
    "link": "link",
    "status": "status",
    "track": "track status",
    "previous": "previous memory",
    "first": "first memory",
    "age": "previous before",
    "ager": "previous before",
    "আমি": "i",
    "আমার": "my",
    "এর": "of",
    "জন্য": "for",
    "কি": "what",
    "কে": "who",
    "আপনি": "you",
    "আপনার": "your",
    "তুমি": "you",
    "তোমার": "your",
    "সালাম": "salam hi greeting",
    "আসসালামু": "salam hi greeting",
    "আলাইকুম": "salam hi greeting",
    "হ্যালো": "hello hi greeting",
    "হাই": "hi greeting",
    "জানতে": "know",
    "চাই": "want",
    "দরকার": "need required",
    "লাগবে": "need required",
    "কত": "how much",
    "কতো": "how much",
    "টাকা": "amount bdt",
    "ফি": "fee charge",
    "চার্জ": "charge fee",
    "খরচ": "cost charge fee",
    "মাশুল": "fee charge",
    "ভ্যাট": "vat",
    "হিসাব": "account",
    "হিসাবের": "account",
    "একাউন্ট": "account",
    "একাউন্টের": "account",
    "অ্যাকাউন্ট": "account",
    "অ্যাকাউন্টের": "account",
    "খুলতে": "open account",
    "খুলবো": "open account",
    "খোলা": "open account",
    "বন্ধ": "closing close",
    "সঞ্চয়ী": "saving savings",
    "সঞ্চয়ী": "saving savings",
    "সেভিংস": "saving savings",
    "চলতি": "current",
    "আমানত": "deposit",
    "ডিপোজিট": "deposit",
    "মেয়াদী": "fixed term",
    "মেয়াদী": "fixed term",
    "সুদ": "interest rate",
    "মুনাফা": "profit interest rate",
    "রেট": "rate interest",
    "হার": "rate",
    "লোন": "loan",
    "ঋণ": "loan",
    "বাড়ি": "home house",
    "বাড়ি": "home house",
    "গাড়ি": "car vehicle auto",
    "গাড়ি": "car vehicle auto",
    "পার্সোনাল": "personal",
    "শিক্ষা": "education student",
    "ছাত্র": "student",
    "কার্ড": "card",
    "ক্রেডিট": "credit",
    "ডেবিট": "debit",
    "প্রিপেইড": "prepaid",
    "পিন": "pin",
    "চেক": "cheque check",
    "বই": "book",
    "এটিএম": "atm",
    "ক্যাশ": "cash",
    "উত্তোলন": "withdrawal",
    "রিপ্লেসমেন্ট": "replacement",
    "পরিবর্তন": "change replacement",
    "সাপ্লিমেন্টারি": "supplementary",
    "বার্ষিক": "annual yearly",
    "বাৎসরিক": "annual yearly",
    "বছর": "year",
    "মাসিক": "monthly",
    "মেয়াদ": "tenure",
    "মেয়াদ": "tenure",
    "রক্ষণাবেক্ষণ": "maintenance",
    "মেইনটেন্যান্স": "maintenance",
    "প্রসেসিং": "processing",
    "নবায়ন": "renewal",
    "ইস্যু": "issue issuance",
    "লিমিট": "limit",
    "শাখা": "branch",
    "ব্রাঞ্চ": "branch",
    "কোথায়": "where location",
    "কোথায়": "where location",
    "ঠিকানা": "address location",
    "যোগাযোগ": "contact",
    "ফোন": "phone number",
    "নম্বর": "number",
    "নাম্বার": "number",
    "হটলাইন": "hotline",
    "ইমেইল": "email",
    "মেইল": "email",
    "সাপোর্ট": "support",
    "অভিযোগ": "complaint",
    "সমস্যা": "problem issue",
    "লেনদেন": "transaction",
    "ব্যর্থ": "failed",
    "কাটা": "deducted",
    "কেটে": "deducted",
    "রিফান্ড": "refund",
    "পাইনি": "not received missing",
    "হারিয়ে": "lost",
    "হারিয়ে": "lost",
    "চুরি": "stolen",
    "ব্লক": "block",
    "অননুমোদিত": "unauthorized fraud",
    "প্রতারণা": "fraud",
    "লগইন": "login",
    "পাসওয়ার্ড": "password",
    "পাসওয়ার্ড": "password",
    "ওটিপি": "otp",
    "সিভিভি": "cvv",
    "এনআইডি": "nid",
    "পাসপোর্ট": "passport",
    "নমিনি": "nominee",
    "কাগজ": "documents required",
    "ডকুমেন্ট": "documents required",
    "ডকুমেন্টস": "documents required",
    "রিটেইল": "retail",
    "এসএমই": "sme",
    "কর্পোরেট": "corporate",
    "ইসলামিক": "islamic",
    "শরিয়াহ": "shariah islamic",
    "শরিয়া": "shariah islamic",
    "আর্মি": "army",
    "সেনাবাহিনী": "army",
    "এয়ার": "air",
    "এয়ার": "air",
    "ফোর্স": "force",
    "বিমানবাহিনী": "air force",
    "নেভি": "navy",
    "নৌবাহিনী": "navy",
    "আবেদন": "apply application",
    "অনলাইন": "online",
    "লিংক": "link",
    "স্ট্যাটাস": "status",
    "আগে": "previous before",
    "আগের": "previous before",
    "প্রথম": "first memory",
}


def normalize_bangla_digits(text):
    return (text or "").translate(BANGLA_DIGITS)


def has_bangla_script(text):
    return bool(re.search(r"[\u0980-\u09ff]", text or ""))


def _phrase_key(text):
    text = normalize_bangla_digits(text).lower()
    text = re.sub(r"[^a-z0-9\u0980-\u09ff]+", " ", text)
    return " ".join(text.split())


def _tokens(text):
    return re.findall(r"[a-z0-9]+|[\u0980-\u09ff]+", text.lower())


def expand_bangla_banglish_text(text):
    original_text = normalize_bangla_digits(text or "")
    normalized_text = _phrase_key(original_text)
    padded_text = f" {normalized_text} "
    expansions = []

    for phrase, english_terms in PHRASE_TRANSLATIONS:
        normalized_phrase = _phrase_key(phrase)

        if normalized_phrase and f" {normalized_phrase} " in padded_text:
            expansions.extend(english_terms.split())

    for token in _tokens(original_text):
        translated_terms = WORD_TRANSLATIONS.get(token)

        if translated_terms:
            expansions.extend(translated_terms.split())

    if not expansions:
        return original_text

    unique_expansions = list(dict.fromkeys(expansions))

    return f"{original_text} {' '.join(unique_expansions)}"


def normalize_for_keyword_matching(text):
    expanded_text = expand_bangla_banglish_text(text)
    expanded_text = expanded_text.lower()
    expanded_text = re.sub(r"[^a-z0-9\u0980-\u09ff]+", " ", expanded_text)
    return " ".join(expanded_text.split())
